{{- if eq .Values.postgres.enabled true }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-postgres
  labels:
    {{- include "european-reference-data-registry.selectorLabels.postgres" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.storageSize }}
{{- end }}
