{{- if eq .Values.keycloak.enabled true }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-keycloak-realm
  labels:
    {{- include "european-reference-data-registry.selectorLabels.keycloak" . | nindent 4 }}
data:
  realm.json: |
    {
      "realm": "ceeds",
      "enabled": true,
      "organizationsEnabled": true,
      "displayName": "CEEDS",
      "sslRequired": "none",
      "registrationAllowed": true,
      "loginWithEmailAllowed": false,
      "duplicateEmailsAllowed": false,
      "clients": [
        {
          "clientId": "ceeds-frontend",
          "name": "CEEDS Frontend",
          "enabled": true,
          "protocol": "openid-connect",
          "publicClient": true,
          "standardFlowEnabled": true,
          "implicitFlowEnabled": false,
          "directAccessGrantsEnabled": false,
          "serviceAccountsEnabled": false,
          "rootUrl": "http://localhost:8080",
          "redirectUris": [
            "http://localhost:5173/*",
            "http://localhost:8080/*"
          ],
          "webOrigins": [
            "http://localhost:5173",
            "http://localhost:8080"
          ],
          "attributes": {
            "pkce.code.challenge.method": "S256",
            "post.logout.redirect.uris": "http://localhost:5173/*##http://localhost:8080/*"
          }
        },
        {
          "clientId": "ceeds-directory",
          "name": "CEEDS organization directory",
          "enabled": true,
          "protocol": "openid-connect",
          "publicClient": false,
          "secret": "{{ .Values.keycloak.directoryClientSecret }}",
          "standardFlowEnabled": false,
          "directAccessGrantsEnabled": false,
          "serviceAccountsEnabled": true
        }
      ],
      "users": [
        {
          "username": "ceeds",
          "enabled": true,
          "credentials": [
            {
              "type": "password",
              "value": "ceeds",
              "temporary": false
            }
          ]
        },
        {
          "username": "service-account-ceeds-directory",
          "enabled": true,
          "serviceAccountClientId": "ceeds-directory",
          "clientRoles": {
            "realm-management": ["view-organizations"]
          }
        }
      ],
      "registrationEmailAsUsername": false,
      "verifyEmail": false,
      "resetPasswordAllowed": false
    }
{{- end }}
