core:
  enabled: false
  image:
    name: ghcr.io/eddie-energy/european-reference-data-registry:snapshot-3e2eef1732d59ae0e83cb5474b5a8d70931c6960
    tag: latest

postgres:
  enabled: true
  storageSize: 10Gi
  image:
    name: postgres
    version: 18.4-alpine
  existingSecret:
    name: postgres-secret
  database: backend
  owner: backend
  storageSize: 10Gi

keycloak:
  enabled: true
  image:
    name: quay.io/keycloak/keycloak
    version: 26.6.0
  httpRelativePath: /auth
  secret:
    name: keycloak-secret

ingress:
  enabled: true
  host: localhost
  tls:
    enabled: false
    clusterIssuer: eddie-letsencrypt-prod
    secretName: eddie-letsencrypt-prod

