management:
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true

spring:
  profiles:
    active: local
  application:
    name: s3-federator
  datasource:
    url: ${s3-federator.db.url}
    username: ${s3-federator.db.username}
    password: ${s3-federator.db.password}
  flyway:
    enabled: true
    locations: 'classpath:db/s3-federator/migration'
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: 'true'

s3-federator:
  db:
    url: jdbc:postgresql://localhost:5440/s3-federator
    username: s3federator
    password: s3federator
